---
- name: This is a hello-world example
  hosts: all
  become: yes
  vars:
    config: cluster.yaml
  
  tasks:
    - name: Loading the configuration settings
      ansible.builtin.include_vars:
        file: "{{ config }}"

    - name: Ansible role for boot strapping the redis sentinel cluster
      ansible.builtin.include_role:
        name: redis_sentinel_cluster
