---
- name: This is a hello-world example
  hosts: redis_replica
  become: yes
  vars: 
    redis_port: 6379
    redis_main_ip: 192.168.56.10
  
  tasks:
    - name: Make sure a service redis is stopped
      ansible.builtin.systemd:
        state: stopped
        name: redis

    - name: "Redis: ensure slaveof is set to redis_main {{ redis_main_ip }} {{ redis_port }}"
      ansible.builtin.lineinfile:
        path: /etc/redis.conf
        regexp: '^slaveof'
        line: "slaveof {{ redis_main_ip }} {{ redis_port }}"
        #insertafter: "slaveof {{ redis_main_ip }} {{ redis_port }}"
        state: present

    - name: Make sure a service redis is running
      ansible.builtin.systemd:
        state: started
        enabled: yes
        name: redis